### ISSUE TITLE
Potential way to escape (Harming Potions)

### ISSUE THREAD

**Issue by Fyshi1** [Jerrylum/GaiasVault#3]
I was wondering how the HarmingPotions were refilled, so I looked it up, and they have to be manually refilled, by a human.
Humans are not the best at remembering stuff i think, and there is no alarm for the guard, which tells him that GaiasVault is low on HarmingPotions. I was thinking about a comperator which looks at the dispenser(HarmingPotions) to remember the Guard when its low on potions.

I dont really know how much of an impact a empty HarmingDispenser will do to GaiasVault, but i think it was worth pointing out.

**Comment by jerbear2008** [comment]
The name is not really accurate if there is no potential escape method.

**Comment by TheDeafCreeper** [comment]
Could add a low inventory notification, not a security issue though.
