### ISSUE TITLE
I get kicked off upon logging in.

### ISSUE THREAD

**Issue by jddicaro** [Jerrylum/GaiasVault#7]
When I log on as warden, it kicks me off. I have the chunkban lever set to enable and warden leave auto panic disabled, yet it kicks me off all the same. Help!

**Comment by TheDeafCreeper** [comment]
Are you on a Vanilla server?

**Comment by jddicaro** [comment]
Yes, ran by either a raspi 4 (8GB) or LAN
sorry for late reply

**Comment by jddicaro** [comment]
I found the Q&A, silly me. I'll close this.
